const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const appFile = ["./src/app.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "Employees API",
    description:
      "Documentation automatically generated by the <b>swagger.autogen</b> module.",
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Employees",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    Employee: {
      name: "Jhon Doe",
      cpf: "357.029.218-56",
      position: "Dev Jr",
      date: "14/06/2019",
      uf: "CE",
      salary: 2000,
      status: "ATIVO",
    },

    AddEmployee: {
      $name: "Jhon Doe",
      $cpf: "357.029.218-56",
      $position: "Dev Jr",
      $date: "14/06/2019",
      $uf: "CE",
      $salary: 2000,
      $status: "ATIVO",
    },

    DeleteEmployee: {
        $cpf: "357.029.218-56",
    },
  },
};

swaggerAutogen(outputFile, appFile, doc).then(() => {
  require("./app.js");
});
